services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_PASSWORD=secret123
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=devops
      - POSTGRES_PASSWORD=secret123
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  pgdata:
